---
- name: installing more than 2 packages
  hosts: mygroup
  become: true
  tasks:
  - name: install httpd package
    yum:
      name: httpd
      state: installed
    notify: start httpd service

  handlers:     
  - name: start httpd service
    service:
      name: httpd
      state: started

